### PR TITLE
Adding a define to not reset the c64 as the ino reset

### PR DESCRIPTION
**Pull request by biappi**
this is just a small feature toggle. my c64 will reset if the line is held high, and i find it really annoying, especially when deploying new code to the arduino, or re-connecting the pc side client.

maybe others can find it useful too.

### CODE REVIEW

**Comment by Larswad** [comment]
Yes, you are right, I also read somewhere older 64's had a different behavior on the reset line. But I never had one to test with. I believe the sd2iec doesn't even care about the reset line at all and maybe there is no actual need.
I kept it just as a way to know when the host computer reset, just in case I ever needed to reset some states or something.

I will merge your addition, but only partly, because what about those Log statements in your push, they were not really part of this right? It looks like you have used them for some debugging?

**Comment by biappi** [comment]
ooops, yeah totatlly debug logging… sorry i didn’t double check the diff i was sending :/

-w

**Comment by Larswad** [comment]
No problem biappi! I wonder if github supports partial marging of a pull request.

**Comment by biappi** [comment]
i think me or you can add a commit on to of the pull-request branch to remove the logs. then merge from the github ui

**Comment by Larswad** [comment]
Hmm, It says i need to have push rights in order to make changes on that branch (which I don't...).

**Comment by Larswad** [comment]
That's it. Thanks.

**Pull request merged**
